[package]
name = "mnist-api"
version = "0.1.0"
edition = "2021"
description = "Simple server that exposes an API for inference on the MNIST dataset"
authors = ["Matthieu Legrand <legmatt0@gmail.com>"] 
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.3.2"
mlp={path="../../models/mlp"}
tch="0.7.0"
tokio = { version = "1", features = ["full"] }
futures-util = {version="0.3"}
async-channel = "1.6"
clap = {version = "3.1", features=["derive"]}