[package]
name = "tch-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.7"
anyhow = "1"
thiserror = "1"
itertools = "0.10"
tch-macros-utils = {path="../macros-utils"}