[package]
name = "unet-train"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.7"
unet = { path="../../models/unet" }
clap = {version="3.1", features=["derive"]}
tch-utils = { path="../../utils"}
anyhow = "1"
tiff = "0.7"
rand = "0.8"
itertools = "0.10"