[package]
name = "mnist-front"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
yew-agent = "0.1"
wasm-logger = "0.2"
log = "0.4"
wasm-bindgen = "0.2"

[target.'cfg(target_arch = "wasm")'.dependencies]
surf = {version="2.3", default-features = false, features=["wasm-client"]}
[target.'cfg(target_arch = "x86_64")'.dependencies]
surf = {version="2.3"}

[dependencies.web-sys]
version = "0.3.4"
features = [
  'CanvasRenderingContext2d',
  'Document',
  'Element',
  'HtmlCanvasElement',
  'Window',
  'ImageData',
  'Location'
]